// nios_II_led.v

// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module nios_II_led (
		input  wire       clk_clk,    // clk.clk
		output wire [9:0] led_export  // led.export
	);

	wire         nios_led_debug_reset_request_reset;                     // nios_led:debug_reset_request -> rst_controller:reset_in0
	wire  [31:0] nios_led_data_master_readdata;                          // mm_interconnect_0:nios_led_data_master_readdata -> nios_led:d_readdata
	wire         nios_led_data_master_waitrequest;                       // mm_interconnect_0:nios_led_data_master_waitrequest -> nios_led:d_waitrequest
	wire         nios_led_data_master_debugaccess;                       // nios_led:debug_mem_slave_debugaccess_to_roms -> mm_interconnect_0:nios_led_data_master_debugaccess
	wire  [17:0] nios_led_data_master_address;                           // nios_led:d_address -> mm_interconnect_0:nios_led_data_master_address
	wire   [3:0] nios_led_data_master_byteenable;                        // nios_led:d_byteenable -> mm_interconnect_0:nios_led_data_master_byteenable
	wire         nios_led_data_master_read;                              // nios_led:d_read -> mm_interconnect_0:nios_led_data_master_read
	wire         nios_led_data_master_readdatavalid;                     // mm_interconnect_0:nios_led_data_master_readdatavalid -> nios_led:d_readdatavalid
	wire         nios_led_data_master_write;                             // nios_led:d_write -> mm_interconnect_0:nios_led_data_master_write
	wire  [31:0] nios_led_data_master_writedata;                         // nios_led:d_writedata -> mm_interconnect_0:nios_led_data_master_writedata
	wire  [31:0] nios_led_instruction_master_readdata;                   // mm_interconnect_0:nios_led_instruction_master_readdata -> nios_led:i_readdata
	wire         nios_led_instruction_master_waitrequest;                // mm_interconnect_0:nios_led_instruction_master_waitrequest -> nios_led:i_waitrequest
	wire  [17:0] nios_led_instruction_master_address;                    // nios_led:i_address -> mm_interconnect_0:nios_led_instruction_master_address
	wire         nios_led_instruction_master_read;                       // nios_led:i_read -> mm_interconnect_0:nios_led_instruction_master_read
	wire         nios_led_instruction_master_readdatavalid;              // mm_interconnect_0:nios_led_instruction_master_readdatavalid -> nios_led:i_readdatavalid
	wire         mm_interconnect_0_debug_avalon_jtag_slave_chipselect;   // mm_interconnect_0:debug_avalon_jtag_slave_chipselect -> debug:av_chipselect
	wire  [31:0] mm_interconnect_0_debug_avalon_jtag_slave_readdata;     // debug:av_readdata -> mm_interconnect_0:debug_avalon_jtag_slave_readdata
	wire         mm_interconnect_0_debug_avalon_jtag_slave_waitrequest;  // debug:av_waitrequest -> mm_interconnect_0:debug_avalon_jtag_slave_waitrequest
	wire   [0:0] mm_interconnect_0_debug_avalon_jtag_slave_address;      // mm_interconnect_0:debug_avalon_jtag_slave_address -> debug:av_address
	wire         mm_interconnect_0_debug_avalon_jtag_slave_read;         // mm_interconnect_0:debug_avalon_jtag_slave_read -> debug:av_read_n
	wire         mm_interconnect_0_debug_avalon_jtag_slave_write;        // mm_interconnect_0:debug_avalon_jtag_slave_write -> debug:av_write_n
	wire  [31:0] mm_interconnect_0_debug_avalon_jtag_slave_writedata;    // mm_interconnect_0:debug_avalon_jtag_slave_writedata -> debug:av_writedata
	wire  [31:0] mm_interconnect_0_nios_led_debug_mem_slave_readdata;    // nios_led:debug_mem_slave_readdata -> mm_interconnect_0:nios_led_debug_mem_slave_readdata
	wire         mm_interconnect_0_nios_led_debug_mem_slave_waitrequest; // nios_led:debug_mem_slave_waitrequest -> mm_interconnect_0:nios_led_debug_mem_slave_waitrequest
	wire         mm_interconnect_0_nios_led_debug_mem_slave_debugaccess; // mm_interconnect_0:nios_led_debug_mem_slave_debugaccess -> nios_led:debug_mem_slave_debugaccess
	wire   [8:0] mm_interconnect_0_nios_led_debug_mem_slave_address;     // mm_interconnect_0:nios_led_debug_mem_slave_address -> nios_led:debug_mem_slave_address
	wire         mm_interconnect_0_nios_led_debug_mem_slave_read;        // mm_interconnect_0:nios_led_debug_mem_slave_read -> nios_led:debug_mem_slave_read
	wire   [3:0] mm_interconnect_0_nios_led_debug_mem_slave_byteenable;  // mm_interconnect_0:nios_led_debug_mem_slave_byteenable -> nios_led:debug_mem_slave_byteenable
	wire         mm_interconnect_0_nios_led_debug_mem_slave_write;       // mm_interconnect_0:nios_led_debug_mem_slave_write -> nios_led:debug_mem_slave_write
	wire  [31:0] mm_interconnect_0_nios_led_debug_mem_slave_writedata;   // mm_interconnect_0:nios_led_debug_mem_slave_writedata -> nios_led:debug_mem_slave_writedata
	wire         mm_interconnect_0_sram_s1_chipselect;                   // mm_interconnect_0:SRAM_s1_chipselect -> SRAM:chipselect
	wire  [31:0] mm_interconnect_0_sram_s1_readdata;                     // SRAM:readdata -> mm_interconnect_0:SRAM_s1_readdata
	wire  [13:0] mm_interconnect_0_sram_s1_address;                      // mm_interconnect_0:SRAM_s1_address -> SRAM:address
	wire   [3:0] mm_interconnect_0_sram_s1_byteenable;                   // mm_interconnect_0:SRAM_s1_byteenable -> SRAM:byteenable
	wire         mm_interconnect_0_sram_s1_write;                        // mm_interconnect_0:SRAM_s1_write -> SRAM:write
	wire  [31:0] mm_interconnect_0_sram_s1_writedata;                    // mm_interconnect_0:SRAM_s1_writedata -> SRAM:writedata
	wire         mm_interconnect_0_sram_s1_clken;                        // mm_interconnect_0:SRAM_s1_clken -> SRAM:clken
	wire         mm_interconnect_0_led_s1_chipselect;                    // mm_interconnect_0:led_s1_chipselect -> led:chipselect
	wire  [31:0] mm_interconnect_0_led_s1_readdata;                      // led:readdata -> mm_interconnect_0:led_s1_readdata
	wire   [1:0] mm_interconnect_0_led_s1_address;                       // mm_interconnect_0:led_s1_address -> led:address
	wire         mm_interconnect_0_led_s1_write;                         // mm_interconnect_0:led_s1_write -> led:write_n
	wire  [31:0] mm_interconnect_0_led_s1_writedata;                     // mm_interconnect_0:led_s1_writedata -> led:writedata
	wire         irq_mapper_receiver0_irq;                               // debug:av_irq -> irq_mapper:receiver0_irq
	wire  [31:0] nios_led_irq_irq;                                       // irq_mapper:sender_irq -> nios_led:irq
	wire         rst_controller_reset_out_reset;                         // rst_controller:reset_out -> [SRAM:reset, debug:rst_n, irq_mapper:reset, led:reset_n, mm_interconnect_0:nios_led_reset_reset_bridge_in_reset_reset, nios_led:reset_n, rst_translator:in_reset]
	wire         rst_controller_reset_out_reset_req;                     // rst_controller:reset_req -> [SRAM:reset_req, nios_led:reset_req, rst_translator:reset_req_in]

	nios_II_led_SRAM sram (
		.clk        (clk_clk),                              //   clk1.clk
		.address    (mm_interconnect_0_sram_s1_address),    //     s1.address
		.clken      (mm_interconnect_0_sram_s1_clken),      //       .clken
		.chipselect (mm_interconnect_0_sram_s1_chipselect), //       .chipselect
		.write      (mm_interconnect_0_sram_s1_write),      //       .write
		.readdata   (mm_interconnect_0_sram_s1_readdata),   //       .readdata
		.writedata  (mm_interconnect_0_sram_s1_writedata),  //       .writedata
		.byteenable (mm_interconnect_0_sram_s1_byteenable), //       .byteenable
		.reset      (rst_controller_reset_out_reset),       // reset1.reset
		.reset_req  (rst_controller_reset_out_reset_req),   //       .reset_req
		.freeze     (1'b0)                                  // (terminated)
	);

	nios_II_led_debug debug (
		.clk            (clk_clk),                                               //               clk.clk
		.rst_n          (~rst_controller_reset_out_reset),                       //             reset.reset_n
		.av_chipselect  (mm_interconnect_0_debug_avalon_jtag_slave_chipselect),  // avalon_jtag_slave.chipselect
		.av_address     (mm_interconnect_0_debug_avalon_jtag_slave_address),     //                  .address
		.av_read_n      (~mm_interconnect_0_debug_avalon_jtag_slave_read),       //                  .read_n
		.av_readdata    (mm_interconnect_0_debug_avalon_jtag_slave_readdata),    //                  .readdata
		.av_write_n     (~mm_interconnect_0_debug_avalon_jtag_slave_write),      //                  .write_n
		.av_writedata   (mm_interconnect_0_debug_avalon_jtag_slave_writedata),   //                  .writedata
		.av_waitrequest (mm_interconnect_0_debug_avalon_jtag_slave_waitrequest), //                  .waitrequest
		.av_irq         (irq_mapper_receiver0_irq)                               //               irq.irq
	);

	nios_II_led_led led (
		.clk        (clk_clk),                             //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),     //               reset.reset_n
		.address    (mm_interconnect_0_led_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_led_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_led_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_led_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_led_s1_readdata),   //                    .readdata
		.out_port   (led_export)                           // external_connection.export
	);

	nios_II_led_nios_led nios_led (
		.clk                                 (clk_clk),                                                //                       clk.clk
		.reset_n                             (~rst_controller_reset_out_reset),                        //                     reset.reset_n
		.reset_req                           (rst_controller_reset_out_reset_req),                     //                          .reset_req
		.d_address                           (nios_led_data_master_address),                           //               data_master.address
		.d_byteenable                        (nios_led_data_master_byteenable),                        //                          .byteenable
		.d_read                              (nios_led_data_master_read),                              //                          .read
		.d_readdata                          (nios_led_data_master_readdata),                          //                          .readdata
		.d_waitrequest                       (nios_led_data_master_waitrequest),                       //                          .waitrequest
		.d_write                             (nios_led_data_master_write),                             //                          .write
		.d_writedata                         (nios_led_data_master_writedata),                         //                          .writedata
		.d_readdatavalid                     (nios_led_data_master_readdatavalid),                     //                          .readdatavalid
		.debug_mem_slave_debugaccess_to_roms (nios_led_data_master_debugaccess),                       //                          .debugaccess
		.i_address                           (nios_led_instruction_master_address),                    //        instruction_master.address
		.i_read                              (nios_led_instruction_master_read),                       //                          .read
		.i_readdata                          (nios_led_instruction_master_readdata),                   //                          .readdata
		.i_waitrequest                       (nios_led_instruction_master_waitrequest),                //                          .waitrequest
		.i_readdatavalid                     (nios_led_instruction_master_readdatavalid),              //                          .readdatavalid
		.irq                                 (nios_led_irq_irq),                                       //                       irq.irq
		.debug_reset_request                 (nios_led_debug_reset_request_reset),                     //       debug_reset_request.reset
		.debug_mem_slave_address             (mm_interconnect_0_nios_led_debug_mem_slave_address),     //           debug_mem_slave.address
		.debug_mem_slave_byteenable          (mm_interconnect_0_nios_led_debug_mem_slave_byteenable),  //                          .byteenable
		.debug_mem_slave_debugaccess         (mm_interconnect_0_nios_led_debug_mem_slave_debugaccess), //                          .debugaccess
		.debug_mem_slave_read                (mm_interconnect_0_nios_led_debug_mem_slave_read),        //                          .read
		.debug_mem_slave_readdata            (mm_interconnect_0_nios_led_debug_mem_slave_readdata),    //                          .readdata
		.debug_mem_slave_waitrequest         (mm_interconnect_0_nios_led_debug_mem_slave_waitrequest), //                          .waitrequest
		.debug_mem_slave_write               (mm_interconnect_0_nios_led_debug_mem_slave_write),       //                          .write
		.debug_mem_slave_writedata           (mm_interconnect_0_nios_led_debug_mem_slave_writedata),   //                          .writedata
		.dummy_ci_port                       ()                                                        // custom_instruction_master.readra
	);

	nios_II_led_mm_interconnect_0 mm_interconnect_0 (
		.clk_0_clk_clk                              (clk_clk),                                                //                            clk_0_clk.clk
		.nios_led_reset_reset_bridge_in_reset_reset (rst_controller_reset_out_reset),                         // nios_led_reset_reset_bridge_in_reset.reset
		.nios_led_data_master_address               (nios_led_data_master_address),                           //                 nios_led_data_master.address
		.nios_led_data_master_waitrequest           (nios_led_data_master_waitrequest),                       //                                     .waitrequest
		.nios_led_data_master_byteenable            (nios_led_data_master_byteenable),                        //                                     .byteenable
		.nios_led_data_master_read                  (nios_led_data_master_read),                              //                                     .read
		.nios_led_data_master_readdata              (nios_led_data_master_readdata),                          //                                     .readdata
		.nios_led_data_master_readdatavalid         (nios_led_data_master_readdatavalid),                     //                                     .readdatavalid
		.nios_led_data_master_write                 (nios_led_data_master_write),                             //                                     .write
		.nios_led_data_master_writedata             (nios_led_data_master_writedata),                         //                                     .writedata
		.nios_led_data_master_debugaccess           (nios_led_data_master_debugaccess),                       //                                     .debugaccess
		.nios_led_instruction_master_address        (nios_led_instruction_master_address),                    //          nios_led_instruction_master.address
		.nios_led_instruction_master_waitrequest    (nios_led_instruction_master_waitrequest),                //                                     .waitrequest
		.nios_led_instruction_master_read           (nios_led_instruction_master_read),                       //                                     .read
		.nios_led_instruction_master_readdata       (nios_led_instruction_master_readdata),                   //                                     .readdata
		.nios_led_instruction_master_readdatavalid  (nios_led_instruction_master_readdatavalid),              //                                     .readdatavalid
		.debug_avalon_jtag_slave_address            (mm_interconnect_0_debug_avalon_jtag_slave_address),      //              debug_avalon_jtag_slave.address
		.debug_avalon_jtag_slave_write              (mm_interconnect_0_debug_avalon_jtag_slave_write),        //                                     .write
		.debug_avalon_jtag_slave_read               (mm_interconnect_0_debug_avalon_jtag_slave_read),         //                                     .read
		.debug_avalon_jtag_slave_readdata           (mm_interconnect_0_debug_avalon_jtag_slave_readdata),     //                                     .readdata
		.debug_avalon_jtag_slave_writedata          (mm_interconnect_0_debug_avalon_jtag_slave_writedata),    //                                     .writedata
		.debug_avalon_jtag_slave_waitrequest        (mm_interconnect_0_debug_avalon_jtag_slave_waitrequest),  //                                     .waitrequest
		.debug_avalon_jtag_slave_chipselect         (mm_interconnect_0_debug_avalon_jtag_slave_chipselect),   //                                     .chipselect
		.led_s1_address                             (mm_interconnect_0_led_s1_address),                       //                               led_s1.address
		.led_s1_write                               (mm_interconnect_0_led_s1_write),                         //                                     .write
		.led_s1_readdata                            (mm_interconnect_0_led_s1_readdata),                      //                                     .readdata
		.led_s1_writedata                           (mm_interconnect_0_led_s1_writedata),                     //                                     .writedata
		.led_s1_chipselect                          (mm_interconnect_0_led_s1_chipselect),                    //                                     .chipselect
		.nios_led_debug_mem_slave_address           (mm_interconnect_0_nios_led_debug_mem_slave_address),     //             nios_led_debug_mem_slave.address
		.nios_led_debug_mem_slave_write             (mm_interconnect_0_nios_led_debug_mem_slave_write),       //                                     .write
		.nios_led_debug_mem_slave_read              (mm_interconnect_0_nios_led_debug_mem_slave_read),        //                                     .read
		.nios_led_debug_mem_slave_readdata          (mm_interconnect_0_nios_led_debug_mem_slave_readdata),    //                                     .readdata
		.nios_led_debug_mem_slave_writedata         (mm_interconnect_0_nios_led_debug_mem_slave_writedata),   //                                     .writedata
		.nios_led_debug_mem_slave_byteenable        (mm_interconnect_0_nios_led_debug_mem_slave_byteenable),  //                                     .byteenable
		.nios_led_debug_mem_slave_waitrequest       (mm_interconnect_0_nios_led_debug_mem_slave_waitrequest), //                                     .waitrequest
		.nios_led_debug_mem_slave_debugaccess       (mm_interconnect_0_nios_led_debug_mem_slave_debugaccess), //                                     .debugaccess
		.SRAM_s1_address                            (mm_interconnect_0_sram_s1_address),                      //                              SRAM_s1.address
		.SRAM_s1_write                              (mm_interconnect_0_sram_s1_write),                        //                                     .write
		.SRAM_s1_readdata                           (mm_interconnect_0_sram_s1_readdata),                     //                                     .readdata
		.SRAM_s1_writedata                          (mm_interconnect_0_sram_s1_writedata),                    //                                     .writedata
		.SRAM_s1_byteenable                         (mm_interconnect_0_sram_s1_byteenable),                   //                                     .byteenable
		.SRAM_s1_chipselect                         (mm_interconnect_0_sram_s1_chipselect),                   //                                     .chipselect
		.SRAM_s1_clken                              (mm_interconnect_0_sram_s1_clken)                         //                                     .clken
	);

	nios_II_led_irq_mapper irq_mapper (
		.clk           (clk_clk),                        //       clk.clk
		.reset         (rst_controller_reset_out_reset), // clk_reset.reset
		.receiver0_irq (irq_mapper_receiver0_irq),       // receiver0.irq
		.sender_irq    (nios_led_irq_irq)                //    sender.irq
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (1),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (nios_led_debug_reset_request_reset), // reset_in0.reset
		.clk            (clk_clk),                            //       clk.clk
		.reset_out      (rst_controller_reset_out_reset),     // reset_out.reset
		.reset_req      (rst_controller_reset_out_reset_req), //          .reset_req
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_in1      (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

endmodule
